//Clients should have the following properties: Autogenerated PK Id, First Name, Last
// Name, DOB, Address, Membership Card Number, Membership Card Validity Date, Rent
// Date and Return Date and FK Movie Id which will be the connection to the Movies table

using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace WebServicesNenadExam5063.Models
{

    public class Client
    {
        [Required]
        public int Id { get; set; }
        [Required]
        [MaxLength(100)]
        public string First_Name { get; set; }
        [Required]
        [MaxLength(200)]
        public string Last_Name { get; set; }
        [Required]
        public string DOB { get; set; }
        [Required]
        [MaxLength(300)]
        public string Adress { get; set; }
        [Required]
        public string Membership_Card_Number { get; set; }
        [Required]
        public string Membership_Card_Validity_Date { get; set; }
        [AllowNull]
        public string Rent_Date { get; set; }
        [AllowNull]
        public string Return_Date { get; set; }
        [AllowNull]
        public int MovieId {  get; set; }
        public Movie Movie { get; set; }


    }
}
