//Movie should have the following properties: Autogenerated PK Id, Name, Director,
// Genre, Year, Rating, Box Office Earnings

using System.ComponentModel.DataAnnotations;

namespace WebServicesNenadExam5063.Models
{
    public class Movie
    {

        [Required]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Genre { get; set; }
        [Required]
        public string Director { get; set; }
        [Required]
        public int Year { get; set; }
        [Required]
        public float Rating { get; set; }
        [Required]
        public int Box_Office_Earning { get; set; }

    }
}
